export const ANT_DETAILS = {
  korean: "군대개미", english: "Army Ant", scientific: "Eciton burchellii",
  rules: [{
    id: "exploration_recruitment", previewId: "ant_exploration", category: "탐색과 모집",
    behaviors: [
      { id: "participation", name: "집단 탐색",
        description: "군대개미는 많은 개체가 함께 사냥에 나서며 넓은 영역을 훑는다. 앞쪽에서 퍼져 나가는 무리와 뒤쪽으로 이어지는 이동길이 연결된다.",
        parameter: { label: "탐색 참여 비율", unit: "퍼센트", min: 20, max: 100, step: 5, decimals: 0, defaultValue: 60 } },
      { id: "walk_speed", name: "보행",
        description: "군대개미는 탐색하거나 먹이를 나르며 길을 오간다. 이동 속도는 개체의 크기와 주변 지형, 다른 개체와의 만남에 따라 달라진다.",
        parameter: { label: "보행 속도", unit: "센티미터/초", min: 2, max: 8, step: 0.5, decimals: 1, defaultValue: 5 } },
      { id: "exploration", name: "탐색 방향",
        description: "군대개미는 더듬이로 주변의 냄새를 감지하며 이동한다. 개체마다 조금씩 다른 방향으로 움직이는 과정이 새로운 곳을 탐색하는 데 이어진다.",
        parameter: { label: "탐색 방향 변화", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 35 } },
    ],
  }, {
    id: "chemical_trails", previewId: "ant_exploration", category: "냄새 길",
    behaviors: [
      { id: "deposit_strength", name: "흔적 형성",
        description: "군대개미는 이동하는 길에 냄새 흔적을 남긴다. 오가는 개체가 흔적을 더하면서 다른 개체도 따라갈 수 있는 길이 이어진다.",
        parameter: { label: "흔적 남기는 양", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 60 } },
      { id: "trail_following", name: "흔적 추종",
        description: "군대개미는 더듬이로 냄새를 감지하며 길을 따라간다. 주변의 냄새 차이에 반응해 방향을 조절하지만, 언제나 가장 짧은 길을 고르는 것은 아니다.",
        parameter: { label: "냄새에 반응하는 정도", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 60 } },
      { id: "trail_half_life", name: "흔적 소실",
        description: "냄새 흔적은 시간이 지나며 약해진다. 개체들이 계속 오가는 길은 흔적이 보충되지만, 발길이 끊긴 길은 점차 희미해진다.",
        parameter: { label: "흔적이 절반으로 줄어드는 시간", unit: "초", min: 4, max: 20, step: 1, decimals: 0, defaultValue: 8 } },
    ],
  }, {
    id: "bidirectional_traffic", previewId: "ant_traffic", category: "양방향 통행",
    behaviors: [
      { id: "yield_difference", name: "마주침과 회피",
        description: "군대개미는 마주 오는 동료를 피해 방향을 조절한다. 나가는 개체가 더 크게 비켜서면서, 돌아오는 개체가 길 가운데로 모이는 통행 양상이 나타난다.",
        parameter: { label: "비켜서는 정도의 차이", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 60 } },
      { id: "food_success", name: "먹이 운반",
        description: "사냥터에서 먹이를 얻은 군대개미는 먹이를 몸 아래에 들고 둥지로 돌아온다. 사냥터로 나가는 개체와 돌아오는 개체가 같은 길을 오간다.",
        parameter: { label: "먹이를 얻는 비율", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 60 } },
      { id: "congestion_slowdown", name: "혼잡과 감속",
        description: "앞쪽에 개체가 몰리면 군대개미는 속도를 줄이거나 옆으로 비켜 간다. 이런 작은 움직임들이 모여 길 전체의 통행에 영향을 준다.",
        parameter: { label: "혼잡에 따른 감속", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 65 } },
    ],
  }, {
    id: "circular_milling", previewId: "ant_mill", category: "원형 행렬",
    behaviors: [
      { id: "loop_half_life", name: "본대와의 단절",
        description: "본대에서 떨어진 군대개미 무리는 원을 그리며 같은 곳을 도는 앤트밀을 만들기도 한다. 본대로 이어지는 길을 잃어도 주변의 냄새 흔적을 따라가는 행동은 계속된다.",
        parameter: { label: "흔적이 절반으로 줄어드는 시간", unit: "초", min: 4, max: 20, step: 1, decimals: 0, defaultValue: 10 } },
      { id: "loop_reinforcement", name: "흔적 보강",
        description: "같은 곳을 지나는 개체들은 그 자리에 냄새 흔적을 더한다. 서로가 남긴 흔적을 계속 따라가면 순환이 유지될 수 있다.",
        parameter: { label: "순환 흔적 보강", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 70 } },
      { id: "external_signal", name: "새 경로의 신호",
        description: "냄새 길이 달라지면 개체들이 따라가는 방향도 바뀔 수 있다. 순환이 얼마나 지속되거나 풀리는지는 주변 조건에 따라 다르다.",
        parameter: { label: "이어지는 새 길의 신호", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 0 } },
    ],
  }],
};
