export const BAT_DETAILS = {
  korean: "멕시코자유꼬리박쥐", english: "Mexican Free-tailed Bat", scientific: "Tadarida brasiliensis",
  rules: [{
    id: "flight_sensing", previewId: "bat_flight", category: "비행과 감각",
    behaviors: [
      { id: "flight_speed", name: "속도와 선회",
        description: "멕시코자유꼬리박쥐는 동굴에서 나와 빠르게 날아간다. 비행 속도와 경로는 상황에 따라 달라지며, 방향을 바꿀 때는 곡선을 그리며 선회한다.",
        parameter: { label: "비행 속도", unit: "미터/초", min: 4, max: 12, step: 0.5, decimals: 1, defaultValue: 9 } },
      { id: "light_level", name: "시각과 반향정위",
        description: "박쥐는 눈으로 주변을 보면서, 자신이 낸 소리의 메아리로도 공간을 살핀다. 어둠 속에서는 이 메아리를 이용해 주변 물체의 위치를 알아낸다.",
        parameter: { label: "주변 밝기", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 30 } },
      { id: "sound_masking", name: "소리 간섭",
        description: "여러 박쥐의 소리가 겹치면 약한 메아리를 구별하기 어려워질 수 있다. 그렇다고 무리 안에서 반향정위가 언제나 불가능한 것은 아니다.",
        parameter: { label: "소리 간섭", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 30 } },
      { id: "social_calls", name: "사회적 발성",
        description: "박쥐는 사회적 상호작용에서도 여러 소리를 낸다. 둥지에서 밀쳐지거나 접촉할 때의 항의 발성은 비행 중 주변을 살피는 반향정위와 구분된다." },
    ],
  }, {
    id: "cave_emergence", previewId: "bat_emergence", category: "동굴 출현",
    behaviors: [
      { id: "emergence_activity", name: "출현 시기",
        description: "박쥐는 해 질 무렵 동굴을 나와 먹이를 찾으러 간다. 출발 시각은 밝기뿐 아니라 계절과 날씨, 새끼를 기르는 상태 등에 따라서도 달라진다.",
        parameter: { label: "출현량", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 60 } },
      { id: "exit_width", name: "출구와 통과",
        description: "많은 박쥐가 한 출구를 통과하면 비행 흐름이 좁은 공간에 모인다. 출구를 지나는 흐름과 개체들이 멈춰 차례를 기다리는 행동은 서로 다르다.",
        parameter: { label: "출구 폭", unit: "미터", min: 3, max: 12, step: 0.5, decimals: 1, defaultValue: 7 } },
      { id: "stream_spread", name: "출현 무리의 확산",
        description: "동굴에서 나온 박쥐 무리는 길게 굽이치는 띠를 이루기도 한다. 언제나 빽빽한 대열을 유지하는 것은 아니며, 밖으로 퍼지는 모습도 나타난다.",
        parameter: { label: "퍼지는 정도", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 30 } },
    ],
  }, {
    id: "neighbor_movement", previewId: "bat_neighbors", category: "집단 이동",
    behaviors: [
      { id: "forward_following", name: "전방 이웃 추종",
        description: "동굴을 나오는 박쥐는 앞에서 나는 이웃의 움직임에 더 강하게 반응한다. 앞선 개체가 방향을 바꾸면 시간 차를 두고 비슷한 방향으로 움직인다.",
        parameter: { label: "앞선 이웃의 영향", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 60 } },
      { id: "near_avoidance", name: "충돌 회피",
        description: "박쥐는 가까운 이웃과 부딪히지 않도록 비행 경로를 조절한다. 빽빽한 무리에서 어떤 감각 정보를 이용하는지는 아직 밝혀지는 중이다.",
        parameter: { label: "근거리 회피", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 50 } },
      { id: "stream_spread", name: "무리 분산",
        description: "동굴을 나올 때의 조밀한 무리는 계속 같은 모양으로 머물지 않는다. 이동 중 느슨하게 퍼지기도 하며, 먹이를 찾는 비행은 출구 주변의 흐름과 다르다.",
        parameter: { label: "퍼지는 정도", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 30 } },
    ],
  }, {
    id: "return_threat", previewId: "bat_return", category: "귀환과 위협",
    behaviors: [
      { id: "entry_speed", name: "동굴 귀환",
        description: "먹이를 찾던 박쥐는 새벽에 동굴로 돌아온다. 입구에 접근하며 비행을 조절하므로, 밖으로 나갈 때의 움직임을 그대로 거꾸로 반복하지는 않는다.",
        parameter: { label: "입구 접근 속도", unit: "미터/초", min: 1, max: 6, step: 0.5, decimals: 1, defaultValue: 3 } },
      { id: "light_context", name: "빛 반응",
        description: "성체 박쥐는 어두운 곳에서 밝은 방향으로 향하기도 하지만, 빛이 강해지면 어두운 쪽을 선택하기도 한다. 빛에 대한 반응은 시간대와 성장 단계에 따라서도 다르다." },
      { id: "threat_response", name: "포식 위험",
        description: "무리에서 떨어진 박쥐는 포식자의 표적이 되기 쉽다. 무리 안에 머무는 이점이 있지만, 공격받을 때 언제나 더 빽빽하게 뭉치는 것은 아니다.",
        parameter: { label: "위협 회피 강도", unit: "퍼센트", min: 0, max: 100, step: 5, decimals: 0, defaultValue: 60 } },
    ],
  }],
};
