export const GRASSHOPPER_DETAILS = {
  korean: "사막메뚜기",
  english: "Desert Locust",
  scientific: "Schistocerca gregaria",
  rules: [{
    id: "ground_movement",
    previewId: "locust_ground",
    category: "걷기와 뛰기",
    behaviors: [
      { id: "development", name: "성장과 이동",
        description: "어린 사막메뚜기는 걷거나 뛰어서 이동한다. 날개가 완성된 성충은 하늘을 날아 이동할 수도 있다." },
      { id: "walk_speed", name: "걸어서 이동하기",
        description: "사막메뚜기는 땅 위를 걸으며 주변을 탐색한다. 걷는 속도와 움직이는 시간은 개체의 상태에 따라 달라진다.",
        parameter: { label: "보행 속도", unit: "센티미터/초", min: 0.5, max: 3,
          step: 0.1, decimals: 1, defaultValue: 1.1 } },
      { id: "pause_duration", name: "멈춤과 출발",
        description: "사막메뚜기는 걷는 동안에도 때때로 멈춘다. 오래 멈춘 뒤에는 이전과 다른 방향으로 출발할 가능성이 커진다.",
        parameter: { label: "쉬는 시간", unit: "초", min: 0.5, max: 4,
          step: 0.5, decimals: 1, defaultValue: 1.5 } },
      { id: "hop_distance", name: "뒷다리로 뛰기",
        description: "사막메뚜기는 뒷다리를 접어 힘을 모은 뒤 땅을 차고 뛰어오른다. 도약하기 전의 몸 방향과 자세가 뛰는 방향에 영향을 준다.",
        parameter: { label: "점프 거리", unit: "센티미터", min: 2, max: 8,
          step: 0.5, decimals: 1, defaultValue: 4 } },
    ],
  }, {
    id: "marching_neighbours",
    previewId: "locust_ground",
    category: "행진하는 무리",
    behaviors: [
      { id: "separation_strength", name: "이웃과의 간격",
        description: "행진하는 사막메뚜기는 가까운 이웃의 움직임에 반응하며 이동한다. 뒤쪽에서 다가오는 개체나 접촉 자극은 멈춰 있던 개체가 출발하는 계기가 되기도 한다.",
        parameter: { label: "간격 벌리기 강도", unit: "퍼센트", min: 0, max: 100,
          step: 1, decimals: 0, defaultValue: 60 } },
      { id: "alignment_strength", name: "방향 맞추기",
        description: "사막메뚜기들은 이웃과 상호작용하며 같은 방향으로 이동하는 행진대를 이룬다. 한 개체의 움직임은 주변 개체의 이동에도 영향을 준다.",
        parameter: { label: "방향 맞추기 강도", unit: "퍼센트", min: 0, max: 100,
          step: 1, decimals: 0, defaultValue: 60 } },
      { id: "attraction_strength", name: "이웃에게 접근",
        description: "무리 생활을 하는 사막메뚜기는 다른 개체에게 다가가는 성향을 보인다. 혼자 생활할 때의 이웃을 피하는 성향과는 다르다.",
        parameter: { label: "이웃 접근 강도", unit: "퍼센트", min: 0, max: 100,
          step: 1, decimals: 0, defaultValue: 30 } },
      { id: "phase_change", name: "밀집과 행동 변화",
        description: "개체들이 모이면 함께 움직이는 양상이 달라질 수 있다. 이웃을 대하는 성향이나 몸의 변화까지 모두 같은 순간에 일어나는 것은 아니다." },
    ],
  }, {
    id: "environment_flight", previewId: "locust_flight", category: "환경과 비행",
    behaviors: [
      { id: "temperature", name: "기온과 활동",
        description: "사막메뚜기의 활동은 몸이 얼마나 따뜻한지에 영향을 받는다. 햇빛은 몸을 데우므로 대기 온도만으로 비행 여부가 정해지는 것은 아니다.",
        parameter: { label: "기온", unit: "°C", min: 18, max: 35, step: 1, decimals: 0, defaultValue: 30 } },
      { id: "wind_speed", name: "바람에 실린 이동",
        description: "날고 있는 사막메뚜기의 이동에는 날갯짓뿐 아니라 바람도 영향을 준다. 바람을 향해 몸을 돌려도 땅에서 본 이동 방향은 달라질 수 있다.",
        parameter: { label: "풍속", unit: "미터/초", min: 0, max: 6, step: 0.5, decimals: 1, defaultValue: 2 } },
      { id: "wind_direction", name: "바람과 비행 방향",
        description: "사막메뚜기 무리는 주로 바람을 따라 이동하지만, 조건에 따라 바람을 거슬러 날기도 한다. 바람만으로 모든 이동 경로를 설명할 수는 없다.",
        parameter: { label: "바람이 향하는 방향", unit: "도", min: 0, max: 360, step: 15, decimals: 0, defaultValue: 0 } },
      { id: "adult_flight", name: "성충의 비행",
        description: "날개가 완성된 성충은 도약한 뒤 비행으로 이어갈 수 있다. 땅에서 걷다 멈추는 행동과 공중에서 날아가는 행동은 구분된다." },
    ],
  }, {
    id: "food_threat", previewId: "locust_ground", interaction: "food_threat", category: "먹이와 위협",
    behaviors: [
      { id: "hunger", name: "허기와 이웃",
        description: "영양 상태는 사막메뚜기가 이웃에게 반응하는 방식에 영향을 준다. 동족을 물거나 뒤에서 다가오는 개체를 피하는 행동은 집단 이동을 촉진할 수 있지만, 행진의 유일한 원인은 아니다.",
        parameter: { label: "영양 부족에 따른 반응", unit: "퍼센트", min: 0, max: 100, step: 1, decimals: 0, defaultValue: 40 } },
      { id: "feeding_duration", name: "먹이에 머물기",
        description: "사막메뚜기는 식물이 있는 곳에서 먹이를 먹는다. 먹이를 먹는 동안의 머무름은 무리가 이동하는 시간과 경로에도 영향을 준다.",
        parameter: { label: "먹이에 머무는 시간", unit: "초", min: 0, max: 5, step: 0.5, decimals: 1, defaultValue: 2 } },
      { id: "escape_strength", name: "위협 피하기",
        description: "다가오는 위협을 감지한 사막메뚜기는 방향을 바꾸거나 뛰어서 피할 수 있다. 외부 위협에 대한 회피와 동료를 따라가거나 피하는 행동은 서로 다른 자극에서 시작된다.",
        parameter: { label: "위협 반응 범위", unit: "센티미터", min: 2, max: 10, step: 0.5, decimals: 1, defaultValue: 6 } },
    ],
  }],
};
