export const KRILL_DETAILS={
  korean:"남극크릴",english:"Antarctic Krill",scientific:"Euphausia superba",
  rules:[{
    id:"swimming_feeding",previewId:"krill_feeding",category:"유영과 섭식",
    behaviors:[
      {id:"swim_speed",name:"배다리 운동",
        description:"크릴은 배다리를 차례로 저어 헤엄친다. 몸의 크기와 탈피 상태, 먹이를 먹은 정도에 따라 유영 능력이 달라진다.",
        parameter:{label:"화면 속 기본 유영 속도",unit:"배",min:0,max:2,step:0.1,decimals:1,defaultValue:1}},
      {id:"food_amount",name:"먹이 구역 체류",
        description:"먹이가 많은 곳에서 천천히 헤엄치고 자주 방향을 바꾸는 행동이 나타난다. 이런 움직임은 먹이 구역을 쉽게 벗어나지 않게 한다.",
        parameter:{label:"화면 속 먹이 농도",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:65}},
      {id:"digestion_rate",name:"섭식과 소화",
        description:"크릴은 가슴다리로 작은 먹이를 모아 먹는다. 배가 찬 개체에서는 배다리를 젓는 빈도와 힘이 줄어드는 모습이 관찰된다.",
        parameter:{label:"화면 속 소화 속도",unit:"배",min:0,max:2,step:0.1,decimals:1,defaultValue:1}},
    ],
  },{
    id:"neighbors",previewId:"krill_social",category:"무리와 간격",
    behaviors:[
      {id:"neighbor_range",name:"이웃 감지",
        description:"크릴은 서로 가까이 모여 방향을 맞추며 헤엄친다. 주변의 빛과 물의 움직임은 이웃을 알아차리는 단서가 될 수 있다.",
        parameter:{label:"화면 속 이웃 범위",unit:"배",min:0.6,max:2.4,step:0.2,decimals:1,defaultValue:1.6}},
      {id:"spacing_response",name:"개체 간격",
        description:"무리 속 크릴 사이에는 간격이 있다. 그 간격은 모든 무리에서 같지 않으며, 밀도와 주변 조건에 따라 달라진다.",
        parameter:{label:"화면 속 가까운 이웃 회피",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:55}},
      {id:"group_attraction",name:"무리의 형태",
        description:"크릴 떼는 작은 무리부터 넓은 층이나 띠까지 다양한 모습을 이룬다. 물의 흐름과 먹이 환경도 무리의 분포에 영향을 준다.",
        parameter:{label:"화면 속 이웃에게 모이기",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:50}},
    ],
  },{
    id:"light_depth",previewId:"krill_light",category:"빛과 수직 이동",
    behaviors:[
      {id:"light_phase",name:"낮밤 수심 변화",
        description:"크릴이 머무는 깊이는 시간과 바다의 조건에 따라 달라진다. 여름철 스코샤해 개활지에서는 밤에 더 깊은 곳에 머문 사례도 있다.",
        parameter:{label:"화면 속 낮에서 밤으로",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:0}},
      {id:"twilight_spacing",name:"새벽·해질녘 간격",
        description:"해가 뜨고 질 무렵에는 무리의 간격과 모습도 달라질 수 있다. 모든 무리가 같은 정도로 빽빽해지는 것은 아니다.",
        parameter:{label:"화면 속 무리 간격",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:50}},
      {id:"night_group",name:"야간 군집",
        description:"어두워져도 크릴 무리가 모두 흩어지는 것은 아니다. 작은 무리가 남거나 무리의 크기와 모양이 달라지는 모습이 나타난다.",
        parameter:{label:"화면 속 밤의 모임",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:50}},
    ],
  },{
    id:"sinking_rest",previewId:"krill_rest",category:"침강과 휴식",
    behaviors:[
      {id:"sinking_rate",name:"수동 침강",
        description:"크릴은 물보다 무거워 헤엄을 멈추면 가라앉는다. 배다리 움직임을 줄인 채 내려가는 행동을 낙하산 침강이라고 한다.",
        parameter:{label:"화면 속 침강 속도",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:50}},
      {id:"fullness",name:"포만 상태",
        description:"배가 찬 크릴은 배다리 운동이 약해지고 침강 행동을 보이기 쉽다. 일정한 포만도에 도달하면 모두 동시에 가라앉는 것은 아니다.",
        parameter:{label:"화면 속 포만 상태",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:70}},
      {id:"swimming_effort",name:"유영 재개",
        description:"배다리를 다시 저으면 가라앉는 움직임을 줄이거나 위로 헤엄칠 수 있다. 모든 크릴이 같은 깊이에서 유영을 재개하는 것은 아니다.",
        parameter:{label:"화면 속 유영 추진",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:70}},
    ],
  },{
    id:"threat_light",previewId:"krill_threat",category:"위협과 발광",
    behaviors:[
      {id:"predator_approach",name:"위협 회피",
        description:"크릴은 위협의 크기와 거리에 따라 피하는 움직임을 달리한다. 급박할 때에는 배와 꼬리를 굽혀 뒤로 빠르게 물러나기도 한다.",
        parameter:{label:"화면 속 위협 접근",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:60}},
      {id:"glow_display",name:"발광기관",
        description:"남극크릴은 몸에 발광기관을 지닌다. 빛이 동료에게 위험을 알리는 경보로 쓰인다고 단정할 수는 없다.",
        parameter:{label:"화면 속 발광 표시",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:60}},
      {id:"recovery_delay",name:"무리 회복",
        description:"위협을 피하며 흩어지는 움직임과 이웃에게 맞추는 움직임이 함께 무리의 형태를 바꾼다. 무리 회복을 하나의 고정된 시간이나 간격으로 설명하기는 어렵다.",
        parameter:{label:"화면 속 회복 지연",unit:"배",min:1,max:5,step:0.5,decimals:1,defaultValue:2}},
    ],
  }],
};
