export const SPINY_LOBSTER_DETAILS={
  korean:"카리브해닭새우",english:"Caribbean Spiny Lobster",scientific:"Panulirus argus",
  rules:[{
    id:"walking",previewId:"lobster_walking",category:"보행과 감각",
    behaviors:[
      {id:"growth",name:"성장과 생활",
        description:"아주 어린 닭새우는 해조류 사이에 홀로 숨어 지낸다. 자라면서 바위틈 같은 은신처를 이용하고 동료와 함께 머무는 행동이 나타난다."},
      {id:"walk_speed",name:"보행",
        description:"닭새우는 걷는다리로 바닥을 딛고 이동한다. 평소의 보행은 위험할 때 꼬리를 튕겨 뒤로 빠져나가는 움직임과 다르다.",
        parameter:{label:"화면 속 보행 속도",unit:"배",min:0,max:2,step:0.1,decimals:1,defaultValue:1}},
      {id:"turn_width",name:"선회",
        description:"일반적인 보행에서는 다리를 움직이며 몸의 방향을 바꾼다. 대열에서는 방향이 바뀌는 동안에도 앞 개체와의 접촉을 유지하려 한다.",
        parameter:{label:"화면 속 선회 경로 폭",unit:"퍼센트",min:30,max:70,step:5,decimals:0,defaultValue:50}},
      {id:"antennae",name:"더듬이의 역할",
        description:"짧은 더듬이에는 동료의 냄새를 감지하는 감각기관이 있다. 길고 단단한 더듬이는 주변을 더듬거나 몸을 지키는 데 쓰인다."},
    ],
  },{
    id:"shelter_cycle",previewId:"lobster_shelter",category:"활동 주기",
    behaviors:[
      {id:"day_rest",name:"주간 은신",
        description:"낮에는 바위틈이나 해면 같은 은신처에서 주로 머문다. 동료와 함께 은신하는 행동은 자란 어린 개체부터 뚜렷해진다."},
      {id:"light_level",name:"야간 출발",
        description:"해가 지면 은신처 밖으로 나와 활동한다. 모든 개체가 같은 순간에 출발하는 것은 아니다.",
        parameter:{label:"화면 속 주변 밝기",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:40}},
      {id:"explore_range",name:"야간 탐색",
        description:"평소 밤에는 은신처 주변을 돌아다니며 먹이를 찾는다. 장거리를 줄지어 이동하는 대이주가 매일 밤 반복되는 것은 아니다.",
        parameter:{label:"화면 속 탐색 범위",unit:"퍼센트",min:30,max:100,step:5,decimals:0,defaultValue:65}},
      {id:"home_memory",name:"은신처 복귀",
        description:"은신처를 찾을 때 익숙한 위치와 동료의 냄새가 단서가 된다. 빈 은신처를 새로 발견해 들어가기도 한다.",
        parameter:{label:"위치를 기억하는 개체 비율",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:75}},
    ],
  },{
    id:"single_file",previewId:"lobster_queue",category:"일렬 대열",
    behaviors:[
      {id:"queue_speed",name:"대열 이동",
        description:"이동하는 닭새우는 동료의 뒤를 따라 일렬 대열을 이룬다. 이 대열은 장거리를 이동하는 무리에서 볼 수 있다.",
        parameter:{label:"화면 속 대열 속도",unit:"배",min:0,max:2,step:0.1,decimals:1,defaultValue:1}},
      {id:"queue_gap",name:"접촉과 간격",
        description:"뒤따르는 개체는 짧은 더듬이와 앞쪽 걷는다리로 앞 개체의 복부에 접촉한다. 이 접촉이 줄을 유지하는 단서가 된다.",
        parameter:{label:"화면 속 대열 간격",unit:"배",min:0.8,max:1.3,step:0.1,decimals:1,defaultValue:1}},
      {id:"follow_response",name:"대열 유지",
        description:"이동 방향이 바뀔 때도 앞 개체와의 접촉을 유지하려 한다. 간격이 벌어지면 속도를 조절하며 다시 가까워진다.",
        parameter:{label:"화면 속 간격 조절 반응",unit:"배",min:0.5,max:2,step:0.1,decimals:1,defaultValue:1}},
      {id:"drag",name:"물의 저항 감소",
        description:"같은 속도라면 줄지어 이동할 때 개체당 받는 물의 저항이 줄어든다. 대열이 끊어지거나 이어지는 과정에서 선두도 바뀔 수 있다."},
    ],
  },{
    id:"chemical_signals",previewId:"lobster_chemical",category:"화학 신호",
    behaviors:[
      {id:"signal_release",name:"동료 유인",
        description:"소변에 담긴 화학 신호는 동료가 머무는 은신처를 찾는 단서가 된다. 줄지어 걸을 때 앞 개체와 접촉하는 행동과는 다른 감각을 이용한다.",
        parameter:{label:"화면 속 신호 방출량",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:65}},
      {id:"water_flow",name:"수류와 신호",
        description:"물속의 냄새는 흐름을 따라 이동한다. 물의 흐름과 주변 지형에 따라 신호가 닿는 곳도 달라진다.",
        parameter:{label:"화면 속 물 흐름",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:50}},
      {id:"disease_cue",name:"감염 신호 감지",
        description:"건강한 닭새우는 감염된 동료의 화학 신호를 감지하고 함께 숨는 것을 피한다. 이 냄새의 분포가 바이러스의 전염 범위와 같은 것은 아니다."},
      {id:"signal_spread",name:"확산과 희석",
        description:"물에 섞인 냄새는 퍼지고 희석된다. 감염 개체가 사라진 뒤 은신처를 다시 이용하기까지 걸리는 시간은 아직 분명하지 않다.",
        parameter:{label:"화면 속 신호 퍼짐",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:45}},
    ],
  },{
    id:"defense",previewId:"lobster_defense",category:"위협과 방어",
    behaviors:[
      {id:"den_threat",name:"은신처 방어",
        description:"바위틈은 몸을 숨기는 데 도움이 된다. 닭새우는 긴 더듬이를 이용해 가까이 다가오는 상대에 맞선다.",
        parameter:{label:"은신처 앞 위협의 접근",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:50}},
      {id:"near_threat",name:"후퇴와 도피",
        description:"근처에 피할 곳이 있으면 은신처로 물러날 수 있다. 급작스러운 자극에는 꼬리를 튕겨 빠르게 뒤로 벗어나기도 한다.",
        parameter:{label:"은신처 근처 위협의 접근",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:65}},
      {id:"open_threat",name:"원형 방어",
        description:"개활지에서는 동료와 모여 긴 더듬이를 바깥으로 향하게 하는 방어 대형을 만들기도 한다. 위협을 받는 모든 개체가 늘 이 대형에 참여하는 것은 아니다.",
        parameter:{label:"개활지 위협의 접근",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:65}},
    ],
  },{
    id:"disease",previewId:"lobster_disease",category:"감염과 은신처 회복",
    behaviors:[
      {id:"disease_pace",name:"감염 진행",
        description:"감염된 어린 닭새우는 병이 진행되며 활동이 줄고 죽을 수 있다. 건강한 동료가 전염성이 생기기 전에 감염 신호를 알아차리는 경우도 있다.",
        parameter:{label:"화면 속 감염 진행 속도",unit:"배",min:0,max:2,step:0.1,decimals:1,defaultValue:1}},
      {id:"avoidance_delay",name:"감염 개체 회피",
        description:"건강한 개체는 감염된 동료와 함께 머무는 것을 피한다. 다른 은신처가 부족해도 밖으로 나와 새로운 곳을 찾는 행동이 나타난다.",
        parameter:{label:"화면 속 회피 반응 지연",unit:"초",min:0.2,max:3,step:0.2,decimals:1,defaultValue:1}},
      {id:"flushing",name:"잔류 신호",
        description:"병든 개체는 폐사하거나 포식자에게 잡아먹혀 사라질 수 있다. 이후 냄새가 줄어드는 과정과 은신처 재사용 시점은 환경에 따라 달라질 수 있다.",
        parameter:{label:"화면 속 신호 세척 흐름",unit:"퍼센트",min:0,max:100,step:5,decimals:0,defaultValue:50}},
      {id:"infection_routes",name:"감염 경로",
        description:"감염은 개체 간 접촉이나 바이러스를 지닌 개체의 유입으로 생길 수 있다. 물을 통한 전염도 어린 개체에서 확인되며, 자라는 단계에 따라 감수성이 다르다."},
    ],
  }],
};
